@startuml deployment-diagram
cloud clients
collections PasteReaders
collections PasteWriters
collections UserServices
collections LoadBalancers
database BLOB
database Metadata
database Users
clients --> LoadBalancers
LoadBalancers --> PasteReaders
LoadBalancers --> PasteWriters
LoadBalancers --> UserServices
PasteReaders --> BLOB
PasteReaders --> Metadata
PasteWriters --> BLOB
PasteWriters --> Metadata
UserServices --> Users
@enduml