# Sample global config for monitoring JHipster applications
global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'tinyurl'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  # - job_name: 'application'

  #   # Override the global default and scrape targets from this job every 5 seconds.
  #   scrape_interval: 5s

  #   # scheme defaults to 'http'.
  #   metrics_path: /management/prometheus
  #   static_configs:
  #     - targets:
  #         # On MacOS, replace localhost by host.docker.internal
  #         - localhost:8080

  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'riak'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    # scheme defaults to 'http'.
    metrics_path: /metrics
    dns_sd_configs:
      - names:
        - 'riak-exporter'
        type: 'A'
        port: 8097
  - job_name: 'resolver'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    # scheme defaults to 'http'.
    metrics_path: /actuator/prometheus
    dns_sd_configs:
      - names:
          - 'resolver'
        type: 'A'
        port: 8081

  - job_name: 'shortener'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    # scheme defaults to 'http'.
    metrics_path: /actuator/prometheus
    dns_sd_configs:
      - names:
          - 'shortener'
        type: 'A'
        port: 8080

  - job_name: 'envoy'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    # scheme defaults to 'http'.
    metrics_path: /stats/prometheus
    dns_sd_configs:
      - names:
          - 'envoy'
        type: 'A'
        port: 9901
