version: "3"

services:
  dynamodb:
    image: amazon/dynamodb-local
    network_mode: host
    ports:
      - 8000:8000

  prometheus:
    image: prom/prometheus:v2.11.1
    volumes:
      - ./src/main/docker/prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    network_mode: host
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    volumes:
      - ./src/main/docker/grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    network_mode: host
    ports:
      - 3000:3000

