version: "3"

services:
  dynamodb:
    image: amazon/dynamodb-local

  prometheus:
    image: prom/prometheus:v2.11.1
    volumes:
      - ./src/main/docker/prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    # networks: 
    #   - local
    network_mode: host

  grafana:
    image: grafana/grafana
    volumes:
      - ./src/main/docker/grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - 9090:9090
    # networks: 
    #   - local
    network_mode: host

# networks:
#   local:
#     driver: host
