version: "3"

services:
  rabbitmq:
    image: rabbitmq:3.11-management
    network_mode: host
    ports:
      - 5672:5672
      - 15672:15672

  dynamodb:
    image: amazon/dynamodb-local
    network_mode: host
    ports:
      - 8000:8000

  prometheus:
    image: prom/prometheus:v2.11.1
    volumes:
      - ./src/main/docker/prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    network_mode: host
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    volumes:
      - ./src/main/docker/grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    network_mode: host
    ports:
      - 3000:3000

  service:
    image: rate-limiting-service
    network_mode: host
    ports:
      - 8080:8080
    profiles: ["perf"]
    depends_on:
      - rabbitmq
      - dynamodb

  worker-1:
    image: rate-limiting-worker
    network_mode: host
    environment:
      - PORT=8081
    ports:
      - 8081:8081
    profiles: ["perf"]
    depends_on:
      - rabbitmq
      - dynamodb

  worker-2:
    image: rate-limiting-worker
    network_mode: host
    environment:
      - PORT=8082
    ports:
      - 8082:8081
    profiles: ["perf"]
    depends_on:
      - rabbitmq
      - dynamodb

  worker-3:
    image: rate-limiting-worker
    network_mode: host
    environment:
      - PORT=8083
    ports:
      - 8083:8081
    profiles: ["perf"]
    depends_on:
      - rabbitmq
      - dynamodb

  worker-4:
    image: rate-limiting-worker
    network_mode: host
    environment:
      - PORT=8084
    ports:
      - 8084:8081
    profiles: ["perf"]
    depends_on:
      - rabbitmq
      - dynamodb

  worker-5:
    image: rate-limiting-worker
    network_mode: host
    environment:
      - PORT=8085
    ports:
      - 8085:8081
    profiles: ["perf"]
    depends_on:
      - rabbitmq
      - dynamodb

