version: "3"
services:
  envoy:
    image: envoyproxy/envoy:v1.13.1
    ports:
      # The HTTP port
      - "80:80"
      # The Admin UI
      - "9901:9901"
    volumes:
      - ./src/main/docker/envoy/envoy.yaml:/etc/envoy/envoy.yaml
  resolver:
    image: gitaroktato/tinyurl/resolver
    ports:
      - "8081"
    environment:
      - 'spring.profiles.active=docker'
  shortener:
    image: gitaroktato/tinyurl/shortener
    ports:
      - "8080"
    environment:
      - 'spring.profiles.active=docker'
  prometheus:
    image: prom/prometheus:v2.11.1
    volumes:
      - ./src/main/docker/prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    # On MacOS, remove next line and replace localhost by host.docker.internal in prometheus/prometheus.yml and
    # grafana/provisioning/datasources/datasource.yml
  grafana:
    image: grafana/grafana:6.2.5
    volumes:
      - ./src/main/docker/grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    ports:
      - 3000:3000
  riak-exporter:
    command: --address=0.0.0.0 --port=8097 --riak=http://coordinator:8098/stats --endpoint=/metrics
    build: ./src/main/docker/riak-exporter
    image: infinityworks/prometheus-riak-exporter:latest
    ports:
      - "9091:8097"
  coordinator:
    image: basho/riak-kv
    ports:
      - "8087:8087"
      - "8098:8098"
    environment:
      - CLUSTER_NAME=riakkv
    labels:
      - "com.basho.riak.cluster.name=riakkv"
    volumes:
      - ./src/main/docker/riak/schemas:/etc/riak/schemas
      - ./src/main/docker/riak/poststart.d/03-bootstrap-my-datatype.sh:/etc/riak/poststart.d/03-bootstrap-my-datatype.sh:ro
  member:
    image: basho/riak-kv
    ports:
      - "8087"
      - "8098"
    labels:
      - "com.basho.riak.cluster.name=riakkv"
    links:
      - coordinator
    depends_on:
      - coordinator
    environment:
      - CLUSTER_NAME=riakkv
      - COORDINATOR_NODE=coordinator

volumes:
  schemas:
    external: false
