{
 "title": "Application Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Shortenings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "max (http_server_requests_seconds_max{job = \"shortener\"}) by (outcome) * 1000"
    }
   ]
  },
  {
   "title": "HTTP Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "ops / s" }
   ],
   "targets": [
    {
     "expr": "max(rate(http_server_requests_seconds_count{job = \"shortener\"}[10s])) by (outcome)"
    }
   ]
  },
  {
   "title": "Shortening Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "ops / s" }
   ],
   "targets": [
    {
     "expr": "rate(application_shortening_total[10s])"
    }
   ]
  },
  {
   "title": "Total Shortenings",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "application_shortening_total" }
   ]
  },
  { "title": "Resolutions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "HTTP Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "max (http_server_requests_seconds_max{job = \"resolver\"}) by (outcome) * 1000"
    }
   ]
  },
  {
   "title": "HTTP Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "ops / s" }
   ],
   "targets": [
    {
     "expr": "max(rate(http_server_requests_seconds_count{job = \"resolver\"}[10s])) by (outcome)"
    }
   ]
  },
  {
   "title": "Resolution Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "ops / s" }
   ],
   "targets": [
    {
     "expr": "rate(application_resolving_total[10s])"
    }
   ]
  },
  {
   "title": "Total Resolutions",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "application_resolving_total" }
   ]
  }
 ]
}