{
 "title": "Riak dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Put  duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "riak_node_put_fsm_time_99 / 1000"
    }
   ]
  },
  {
   "title": "Get duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "riak_node_get_fsm_time_99 / 1000"
    }
   ]
  },
  {
   "title": "Siblings max / min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "ops / min" }
   ],
   "targets": [
    { "expr": "riak_node_get_fsm_siblings_100" }
   ]
  },
  {
   "title": "Read / Write Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "ops / s" }
   ],
   "targets": [
    { "expr": "riak_node_gets / 60", "legendFormat": "gets" },
    { "expr": "riak_node_puts / 60", "legendFormat": "puts" }
   ]
  }
 ]
}