{
 "title": "APISIX Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP Latency Distribution",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(apisix_http_latency_bucket{type=\"request\"}[1m]))",
     "legendFormat": "{{route}} -> {{node}}"
    }
   ]
  },
  {
   "title": "HTTP Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    { "expr": "rate(apisix_http_status[1m])", "legendFormat": "{{route}} - {{code}}" }
   ]
  },
  {
   "title": "HTTP Responses - Users",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(apisix_http_status{route=\"user\"}) by (code, route)",
     "legendFormat": "HTTP {{code}}"
    }
   ]
  },
  {
   "title": "HTTP Responses - Paste reads",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(apisix_http_status{route=\"pasteread\"}) by (code, route)",
     "legendFormat": "HTTP {{code}}"
    }
   ]
  },
  {
   "title": "HTTP Responses - Paste writes",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(apisix_http_status{route=\"pastewrite\"}) by (code, route)",
     "legendFormat": "HTTP {{code}}"
    }
   ]
  }
 ]
}