[http.services]
  [http.services.service.loadBalancer]
    [http.services.service.loadBalancer.healthCheck]
      path = "/ping"
      interval = "5s"
      timeout = "2s"
    [[http.services.service.loadBalancer.servers]]
      url = "http://localhost:8070/"
    [[http.services.service.loadBalancer.servers]]
      url = "http://localhost:8071/"
      
[http.routers]
  [http.routers.service]
    entryPoints = ["http"]
    rule = "PathPrefix(`/`)"
    service = "service"
