name: Build TinyURL

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: chmod
        run: chmod +x ./tinyurl/gradlew
      - name: Build with Gradle
        run: ./tinyurl/gradlew build